settings:
  web:
    label: Web
  camera:
    label: Camera
  remote_access:
    label: Remote Access
  snapmaker_components:
    label: Snapmaker Components
  print_preferences:
    label: Print Preferences
  tweaks:
    label: Tweaks
  troubleshooting:
    label: Troubleshooting
  monitoring_debugging:
    label: Monitoring & Debugging
